import {setupFeatures} from './features.js';
let features;
import {blank,live,today,validData,merge,seal,unseal} from './data.js';
import {API_URL} from './config.js';
const $ = s => document.querySelector(s), KEY='mais-uma-data-v1', SETTINGS='mais-uma-cloud-v1';
const fmt = n => Number(n).toLocaleString('pt-BR',{maximumFractionDigits:2});
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateFmt = d => new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'});
let data=blank(),selected='',type='training',editing=null,connection=null,busy=false,timer,toastTimer,storageProblem=false;
try { const saved=localStorage.getItem(KEY); if(saved) {data=JSON.parse(saved);if(!validData(data))throw Error();}selected=localStorage.getItem('mais-uma-person') || ''; } catch { storageProblem=true; }
try { const key=location.hash.slice(1); connection=/^[a-f0-9]{64}$/.test(key)?{key}:JSON.parse(localStorage.getItem(SETTINGS)||'null');if(connection&&!/^[a-f0-9]{64}$/.test(connection.key))connection=null;if(connection)localStorage.setItem(SETTINGS,JSON.stringify(connection)); } catch {}
const defaults=['Supino reto','Supino inclinado','Agachamento','Leg press','Puxada na frente','Remada baixa','Desenvolvimento','Elevação lateral','Rosca direta','Tríceps na polia','Cadeira extensora','Mesa flexora','Levantamento terra','Panturrilha'];
function persist(){try{localStorage.setItem(KEY,JSON.stringify(data));localStorage.setItem('mais-uma-person',selected);storageProblem=false;return true;}catch{storageProblem=true;toast('Não foi possível salvar neste aparelho. Baixe um backup antes de sair.');return false;}}
function toast(message,undo){clearTimeout(toastTimer);$('#toast').textContent=message;if(undo){const b=document.createElement('button');b.textContent='Desfazer';b.onclick=()=>{undo();$('#toast').hidden=true;};$('#toast').append(b);}$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,undo?10000:6500);}
function status(text,kind=''){ $('#cloud-status').textContent=text;$('#cloud-button').className='quiet '+kind; }
function commit(){persist();render();if(connection){status('Alterações para sincronizar');clearTimeout(timer);timer=setTimeout(sync,700);}}
function resetForm(){editing=null;$('#entry-form').reset();$('#date').value=today();$('#date').max=today();$('#cancel-edit').hidden=true;$('#save-entry').innerHTML='Salvar registro <span>↗</span>';$('#form-title').textContent=type==='training'?'O que rendeu hoje?':'Como está seu peso?';$('#form-error').textContent='';features?.reset();lastExercise();}
function setType(next){type=next;$('#tab-training').classList.toggle('active',type==='training');$('#tab-body').classList.toggle('active',type==='body');$('#tab-training').setAttribute('aria-pressed',type==='training');$('#tab-body').setAttribute('aria-pressed',type==='body');$('#exercise-fields').hidden=type!=='training';$('#sets-fields').hidden=type!=='training';$('#exercise').required=type==='training';$('#sets').disabled=type!=='training';$('#reps').disabled=type!=='training';$('#weight-label').textContent=type==='training'?'Carga (kg)':'Seu peso (kg)';$('#weight-help').textContent=type==='training'?'Use sempre o mesmo critério: total ou por lado.':'Se puder, pese-se em condições parecidas.';$('#exercise-filter').hidden=type!=='training';$('#exercise-filter').value='';resetForm();render();}
function personEntries(){return live(data.entries).filter(e=>e.personId===selected&&e.type===type).sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt-a.updatedAt);}
function render(){
 const people=live(data.people);if(!people.some(p=>p.id===selected))selected=people[0]?.id||'';
 $('#people').innerHTML=people.length?people.map(p=>`<button class="person ${p.id===selected?'selected':''}" data-person="${esc(p.id)}" aria-pressed="${p.id===selected}"><span class="avatar">${esc(p.name.slice(0,1).toUpperCase())}</span>${esc(p.name)}</button>`).join(''):'<span class="subtle">Comece adicionando seu nome →</span>';
 $('#person-caption').textContent=people.find(p=>p.id===selected)?.name||'';
 const all=personEntries(),chosen=$('#exercise-filter').value;
 const exercises=[...new Set(all.map(e=>e.exercise))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
 $('#exercise-filter').innerHTML='<option value="">Todos os exercícios</option>'+exercises.map(e=>`<option value="${esc(e)}">${esc(e)}</option>`).join('');if(exercises.includes(chosen))$('#exercise-filter').value=chosen;
 $('#exercise-options').innerHTML=[...new Set([...defaults,...live(data.entries).filter(e=>e.type==='training').map(e=>e.exercise)])].sort().map(e=>`<option value="${esc(e)}"></option>`).join('');
 const filter=type==='training'?$('#exercise-filter').value:'',list=all.filter(e=>!filter||e.exercise===filter),last=list[0];
 $('#stat-one-label').textContent=type==='training'?'Última carga':'Último peso';$('#stat-one').innerHTML=last?`${fmt(last.weight)}<em>kg</em>`:'—';$('#stat-one-detail').textContent=last?(type==='training'?last.exercise+' · ':'')+dateFmt(last.date):'Seu primeiro registro começa aqui.';
 $('#stat-two-label').textContent=type==='training'?'Treinos anotados':'Desde o primeiro registro';
 const delta=list.length>1?last.weight-list.at(-1).weight:null;
 $('#stat-two').innerHTML=type==='training'?new Set(list.map(e=>e.date)).size:delta===null?'—':`${delta>0?'+':''}${fmt(delta)}<em>kg</em>`;
 $('#stat-two-detail').textContent=type==='training'?'dias de treino':list.length+' pesagens anotadas';
 $('#record-count').textContent=list.length;
 $('#records').innerHTML=list.length?list.map(e=>{const d=new Date(e.date+'T12:00:00');return `<article class="record"><div class="record-date">${d.getDate()}<small>${d.toLocaleDateString('pt-BR',{month:'short'}).replace('.','')} ${String(d.getFullYear()).slice(2)}</small></div><div><h3>${esc(type==='training'?e.exercise:'Peso corporal')}</h3><p>${type==='training'?esc(features?.describe(e)||`${e.sets} séries × ${e.reps} repetições`):dateFmt(e.date)}${e.note?' · '+esc(e.note):''}</p></div><div class="record-right"><span class="record-weight">${fmt(e.weight)} <small>kg</small></span><div class="record-actions"><button data-edit="${esc(e.id)}" aria-label="Editar registro de ${esc(e.exercise||'peso corporal')} em ${e.date}">Editar</button><button data-delete="${esc(e.id)}" aria-label="Excluir registro de ${esc(e.exercise||'peso corporal')} em ${e.date}">Excluir</button></div></div></article>`;}).join(''):`<div class="empty"><div class="empty-icon" aria-hidden="true">${type==='training'?'kg.':'↗'}</div><h3>${people.length?'Ainda não tem nada por aqui.':'O caderno está aberto.'}</h3><p>${people.length?(type==='training'?'Anote o primeiro exercício. No próximo treino, você já sabe de onde partir.':'Registre seu peso para começar a acompanhar sua evolução.'):'Adicione seu nome e o do seu amigo. Cada um fica com seu próprio histórico.'}</p></div>`;
 drawChart((type==='body'||filter)?list:[]);lastExercise();features?.render();
}
function drawChart(list){$('#chart-wrap').hidden=list.length<2;if(list.length<2)return;const points=list.slice(0,30).reverse(),lo=Math.min(...points.map(e=>e.weight)),hi=Math.max(...points.map(e=>e.weight)),range=hi-lo||2;const xy=points.map((e,i)=>[42+i*500/(points.length-1),120-(e.weight-lo)*85/range]);$('#chart-title').textContent=type==='body'?'Seu peso ao longo do tempo':$('#exercise-filter').value+' · últimas cargas';$('#chart').innerHTML=`<svg viewBox="0 0 568 160" role="img" aria-label="Evolução de ${fmt(points[0].weight)} para ${fmt(points.at(-1).weight)} quilos, nos últimos ${points.length} registros"><line x1="42" y1="120" x2="542" y2="120" stroke="#dedfd5"/><line x1="42" y1="35" x2="542" y2="35" stroke="#dedfd5" stroke-dasharray="3 5"/><text x="0" y="124">${fmt(lo)}</text><text x="0" y="39">${fmt(lo+range)}</text><polyline points="${xy.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#285944" stroke-width="2.5" stroke-linejoin="round"/>${xy.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="3.5" fill="#285944"><title>${dateFmt(points[i].date)}: ${fmt(points[i].weight)} kg</title></circle>`).join('')}<text x="42" y="150">${dateFmt(points[0].date)}</text><text x="542" y="150" text-anchor="end">${dateFmt(points.at(-1).date)}</text></svg>`;}
function lastExercise(){const ex=$('#exercise').value.trim().toLocaleLowerCase('pt-BR');const prev=live(data.entries).filter(e=>e.personId===selected&&e.type==='training'&&e.exercise.toLocaleLowerCase('pt-BR')===ex).sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt-a.updatedAt)[0];$('#last-exercise').textContent=prev?`Última vez: ${fmt(prev.weight)} kg · ${prev.sets} × ${prev.reps} · ${dateFmt(prev.date)}`:'Escolha um exercício ou escreva um novo.';}
$('#people').onclick=e=>{const b=e.target.closest('[data-person]');if(!b)return;selected=b.dataset.person;features?.personChanged();resetForm();persist();render();};
$('#add-person').onclick=()=>{$('#person-name').value='';$('#person-error').textContent='';$('#person-dialog').showModal();};
$('#person-form').onsubmit=e=>{e.preventDefault();const name=$('#person-name').value.trim();if(!name)return;if(live(data.people).some(p=>p.name.toLocaleLowerCase('pt-BR')===name.toLocaleLowerCase('pt-BR'))){$('#person-error').textContent='Já existe alguém com esse nome. Use um apelido para diferenciar.';return;}const p={id:crypto.randomUUID(),name,updatedAt:Date.now()};data.people.push(p);selected=p.id;features?.personChanged();resetForm();commit();$('#person-dialog').close();toast(`${name} entrou no caderno.`);};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
$('#tab-training').onclick=()=>setType('training');$('#tab-body').onclick=()=>setType('body');$('#exercise-filter').onchange=render;$('#exercise').oninput=lastExercise;$('#cancel-edit').onclick=resetForm;
for(const [id,sign] of [['plus',1],['minus',-1]])$('#'+id).onclick=()=>{const n=Number($('#weight').value.replace(',','.'))||0;$('#weight').value=fmt(Math.max(type==='body'?1:0,Math.min(2000,Math.round((n+sign*(type==='body'?.1:1))*100)/100))).replace(/\./g,'');};
$('#entry-form').onsubmit=e=>{e.preventDefault();$('#form-error').textContent='';if(!selected){$('#form-error').textContent='Adicione uma pessoa antes de salvar.';$('#person-dialog').showModal();return;}const raw=$('#weight').value.trim(),weight=Number(raw.replace(',','.'));if(!/^\d+(?:[.,]\d{1,2})?$/.test(raw)||weight<(type==='body'?1:0)||weight>2000){$('#form-error').textContent='Informe um peso válido em kg (até duas casas decimais).';return;}const exercise=type==='training'?$('#exercise').value.trim():'';if(type==='training'&&!exercise){$('#form-error').textContent='Informe o exercício.';return;}const date=$('#date').value;if(date>today()){$('#form-error').textContent='Escolha hoje ou uma data anterior.';return;}const canonical=live(data.entries).find(x=>x.type==='training'&&x.exercise.toLocaleLowerCase('pt-BR')===exercise.toLocaleLowerCase('pt-BR'))?.exercise||exercise;const row={id:editing||crypto.randomUUID(),personId:selected,type,exercise:canonical,weight,sets:type==='training'?Number($('#sets').value):0,reps:type==='training'?Number($('#reps').value):0,date,note:$('#note').value.trim(),updatedAt:Date.now(),...features?.entryExtras()};const updated=editing!==null;data.entries=data.entries.filter(x=>x.id!==row.id);data.entries.push(row);features?.saved();commit();resetForm();toast(storageProblem?'Registro em memória. Baixe um backup antes de sair.':updated?'Registro atualizado.':'Anotado. Mais uma!');};
$('#records').onclick=e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){const row=data.entries.find(x=>x.id===edit.dataset.edit);editing=row.id;$('#exercise').value=row.exercise;$('#weight').value=String(row.weight).replace('.',',');$('#sets').value=row.sets;$('#reps').value=row.reps;$('#date').value=row.date;$('#note').value=row.note;features?.edit(row);$('#cancel-edit').hidden=false;$('#save-entry').textContent='Salvar alterações';$('#form-title').textContent='Ajustar registro';$('#weight').focus();$('#entry-form').scrollIntoView({behavior:'smooth',block:'center'});lastExercise();}if(del){const row=data.entries.find(x=>x.id===del.dataset.delete);row.deleted=true;row.updatedAt=Date.now();if(editing===row.id)resetForm();commit();toast('Registro excluído.',()=>{const current=data.entries.find(x=>x.id===row.id);current.deleted=false;current.updatedAt=Date.now();commit();});}};
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`mais-uma-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup baixado. Ele contém os registros sem criptografia.');};
$('#import').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5000000)throw Error('Escolha um arquivo de até 5 MB.');const incoming=JSON.parse(await f.text());if(!validData(incoming))throw Error('Este arquivo não é um backup válido do Mais uma.');data=merge(data,incoming);commit();toast('Backup restaurado. Registros repetidos foram combinados.');}catch(err){toast(err.message);}e.target.value='';};
async function remote(c){const res=await fetch(API_URL,{headers:{'X-Notebook':c.key},cache:'no-store',signal:AbortSignal.timeout(20000)});if(!res.ok)throw Error(res.status===401||res.status===403?'Link de acesso inválido. Abra o link original do caderno.':'Não foi possível acessar a nuvem. Seus registros continuam neste aparelho.');const envelope=await res.json();return {data:envelope?await unseal(envelope,c.key):blank(),etag:res.headers.get('X-Notebook-Version')};}
async function writeRemote(c,d,etag){const envelope=await seal(d,c.key);const res=await fetch(API_URL,{method:'PUT',headers:{'Content-Type':'application/json','X-Notebook':c.key,...(etag?{'If-Match':etag}:{'If-None-Match':'*'})},body:JSON.stringify(envelope),signal:AbortSignal.timeout(20000)});if(res.status===409)return false;if(!res.ok)throw Error('Não foi possível sincronizar. Seus registros continuam neste aparelho.');return true;}
async function sync(){if(!connection||busy)return;busy=true;const c=connection;status('Sincronizando…');let pending=false;try{for(let attempt=0;attempt<4;attempt++){const incoming=await remote(c);if(connection!==c)return;data=merge(data,incoming.data);persist();render();const snapshot=JSON.stringify(data);if(snapshot!==JSON.stringify(merge(incoming.data,blank()))){if(!await writeRemote(c,data,incoming.etag))continue;}if(connection!==c)return;pending=snapshot!==JSON.stringify(data);status(pending?'Alterações para sincronizar':'Sincronizado',pending?'':'connected');if($('#cloud-dialog').open&&$('#cloud-error'))$('#cloud-error').textContent='';return;}throw Error('O caderno está sendo atualizado. Tentaremos novamente em alguns segundos.');}catch(err){status('Pendente · tentar novamente','error-state');if($('#cloud-dialog').open&&$('#cloud-error'))$('#cloud-error').textContent=err.message;}finally{busy=false;if(pending){clearTimeout(timer);timer=setTimeout(sync,800);}}}
function notebookLink(){return `${location.origin}${location.pathname}#${connection.key}`;}
function openCloud(){
 $('#cloud-content').innerHTML=connection?`<div class="connection-banner">Seu caderno já está conectado. Compartilhe o link abaixo com seu amigo e adicionem os nomes de vocês.</div><label for="share-link">Link do caderno</label><input id="share-link" readonly value="${esc(notebookLink())}"><button id="copy-link" class="primary">Copiar link para meu amigo</button><button class="secondary" id="sync-now">Sincronizar agora</button><p class="error" id="cloud-error" role="alert"></p><p class="cloud-help">Quem tiver este link pode ver e editar todos os perfis. Guarde-o e compartilhe apenas com seu amigo. Os dados são criptografados antes de serem enviados.</p><p class="hint">A sincronização acontece ao salvar e a cada 30 segundos com o site aberto. Não precisa de conta, senha ou token.</p>`:`<div class="connection-banner">Abra o link completo do seu caderno para conectar este aparelho automaticamente.</div><form id="access-form"><label for="access-link">Já recebeu o link?</label><input id="access-link" placeholder="Cole aqui o link do caderno" required><button class="primary" type="submit">Abrir meu caderno</button><p class="error" id="cloud-error" role="alert"></p></form><p class="cloud-help">Você também pode anotar sem conexão neste aparelho e baixar um backup. Os registros só são compartilhados depois que você abre o link do caderno.</p>`;
 if(connection){$('#copy-link').onclick=async()=>{try{await navigator.clipboard.writeText(notebookLink());toast('Link copiado. Envie para seu amigo.');}catch{$('#share-link').select();toast('Selecione e copie o link acima.');}};$('#sync-now').onclick=sync;}
 else $('#access-form').onsubmit=async e=>{e.preventDefault();let key;try{const url=new URL($('#access-link').value.trim());if(url.origin!==location.origin)throw Error();key=url.hash.slice(1);if(!/^[a-f0-9]{64}$/.test(key))throw Error();}catch{$('#cloud-error').textContent='Cole o link completo do caderno.';return;}const candidate={key};try{await remote(candidate);connection=candidate;localStorage.setItem(SETTINGS,JSON.stringify(candidate));history.replaceState(null,'','#'+key);await sync();openCloud();}catch(err){$('#cloud-error').textContent=err.message;}};
 if(!$('#cloud-dialog').open)$('#cloud-dialog').showModal();
}
$('#cloud-button').onclick=openCloud;
window.addEventListener('online',()=>sync());document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync();});setInterval(()=>{if(!document.hidden)sync();},30000);
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{const other=JSON.parse(e.newValue);if(validData(other)){data=merge(data,other);render();}}catch{}}});
features=setupFeatures({data:()=>data,person:()=>selected,type:()=>type,commit,toast,reset:resetForm,setType});
setType('training');if(connection)sync();if(storageProblem)toast('O armazenamento local não pôde ser lido. Restaure um backup ou conecte a nuvem.');


