import {live,today} from './data.js';
export function setupFeatures(ctx){
 const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let detailed=false,queue=[],active=-1,planEdit=null,personEdit=null,installPrompt=null;
 const pref=(()=>{try{return JSON.parse(localStorage.getItem('mais-uma-options')||'{}');}catch{return {};}})();
 const savePref=()=>localStorage.setItem('mais-uma-options',JSON.stringify(pref));
 $('.people-bar').insertAdjacentHTML('beforeend','<button id="edit-person" class="text-button">Editar perfil</button>');
 $('.section-bar').insertAdjacentHTML('afterend',`<details class="extras"><summary>Opções de treino <span>fichas, descanso e recordes</span></summary><div class="extras-grid"><section><h3>Seu próximo treino</h3><div class="tool-row"><button id="new-plan" class="secondary">Criar ficha A/B/C</button><button id="repeat-workout" class="secondary">Repetir último treino</button></div><div id="plans"></div><label class="check-label"><input type="checkbox" id="show-records" ${pref.records?'checked':''}>Mostrar meus recordes</label><div id="personal-records"></div></section><section><h3>Descanso</h3><p class="hint">Opcional. O relógio continua contando se você sair da aba.</p><div class="tool-row">${[60,90,120].map(n=>`<button class="secondary" data-rest="${n}">${n}s</button>`).join('')}</div><div class="timer-line"><output id="rest-time" aria-label="Tempo restante">00:00</output><button id="pause-rest" class="text-button">Pausar</button><button id="reset-rest" class="text-button">Zerar</button></div><p id="rest-message" role="status" class="hint"></p><button id="install-app" class="text-button">Instalar no celular</button></section></div></details><section id="workout-queue" class="workout-queue" hidden></section>`);
 $('#sets-fields').insertAdjacentHTML('afterend','<div id="detail-option"><label class="check-label"><input type="checkbox" id="detailed">Carga diferente em cada série</label><div id="detail-panel" hidden><p class="hint">Preencha cada série. O resumo e o gráfico usam a maior carga.</p><div id="series-rows"></div><button type="button" id="add-series" class="text-button">＋ Adicionar série</button></div></div>');
 document.body.insertAdjacentHTML('beforeend',`<dialog id="feature-dialog"><div class="dialog-heading"><h2 id="feature-title"></h2><button id="close-feature" class="icon-button" aria-label="Fechar">×</button></div><div id="feature-content"></div></dialog>`);
 const modal=(title,html)=>{$('#feature-title').textContent=title;$('#feature-content').innerHTML=html;if(!$('#feature-dialog').open)$('#feature-dialog').showModal();};
 $('#close-feature').onclick=()=>$('#feature-dialog').close();
 const training=()=>live(ctx.data().entries).filter(e=>e.personId===ctx.person()&&e.type==='training').sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt-a.updatedAt);
 function rows(values){$('#series-rows').innerHTML=values.map((s,i)=>`<div class="series-row"><span>${i+1}</span><label><span class="sr-only">Carga da série ${i+1}</span><input class="series-weight" inputmode="decimal" value="${s.weight}" placeholder="kg" required></label><label><span class="sr-only">Repetições da série ${i+1}</span><input class="series-reps" type="number" min="1" max="500" value="${s.reps}" required></label><button type="button" data-remove-series="${i}" aria-label="Remover série ${i+1}">×</button></div>`).join('');}
 function readRows(){return [...$('#series-rows').children].map(r=>({weight:Number(r.querySelector('.series-weight').value.replace(',','.')),reps:Number(r.querySelector('.series-reps').value)}));}
 function toggle(on,values){detailed=on;$('#detailed').checked=on;$('#detail-panel').hidden=!on;$('#weight').required=!on;for(const el of ['#weight-label','.weight-control','#weight-help'])$(el).hidden=on;$('#sets-fields').hidden=on||ctx.type()!=='training';if(on)rows(values||Array.from({length:Math.min(20,Math.max(1,Number($('#sets').value)||3))},()=>({weight:Number($('#weight').value.replace(',','.'))||0,reps:Number($('#reps').value)||12})));else $('#series-rows').innerHTML='';}
 $('#detailed').onchange=e=>toggle(e.target.checked);$('#add-series').onclick=()=>{const s=readRows();if(s.length>=100)return ctx.toast('Máximo de 100 séries.');s.push(s.at(-1)||{weight:0,reps:12});rows(s);};
 $('#series-rows').onclick=e=>{const b=e.target.closest('[data-remove-series]');if(!b)return;const s=readRows();if(s.length===1)return;s.splice(Number(b.dataset.removeSeries),1);rows(s);};
 $('#entry-form').addEventListener('submit',e=>{if(!detailed||ctx.type()!=='training')return;const s=readRows();const invalid=[...document.querySelectorAll('.series-weight')].some(i=>!/^\d+(?:[.,]\d{1,2})?$/.test(i.value.trim()));if(invalid||!s.length||s.some(x=>!Number.isFinite(x.weight)||x.weight<0||x.weight>2000||!Number.isInteger(x.reps)||x.reps<1||x.reps>500)){e.preventDefault();e.stopImmediatePropagation();$('#form-error').textContent='Confira o peso e as repetições de cada série.';return;}$('#weight').value=String(Math.max(...s.map(x=>x.weight)));$('#sets').value=s.length;$('#reps').value=s[0].reps;},true);
 function loadExercise(item,index){active=index;ctx.reset();$('#exercise').value=item.exercise;$('#weight').value=item.weight??'';$('#sets').value=item.sets||3;$('#reps').value=item.reps||12;if(item.series?.length)toggle(true,item.series);$('#exercise').dispatchEvent(new Event('input'));renderQueue();$('#entry-form').scrollIntoView({behavior:'smooth',block:'start'});}
 function startQueue(items){queue=items.map(x=>({...x}));if(queue.length)loadExercise(queue[0],0);}
 function renderQueue(){$('#workout-queue').hidden=!queue.length||ctx.type()!=='training';$('#workout-queue').innerHTML=`<div class="queue-title"><strong>Treino em andamento</strong><button id="end-queue" class="text-button">Fechar ficha</button></div><p class="hint">Escolha um exercício e ajuste os valores. Só conta como treino depois de salvar.</p><div class="queue-items">${queue.map((e,i)=>`<button data-queue="${i}" class="secondary ${active===i?'chosen':''}">${e.done?'✓ ':''}${esc(e.exercise)}</button>`).join('')}</div>`;$('#end-queue').onclick=()=>{queue=[];renderQueue();};}
 $('#workout-queue').onclick=e=>{const b=e.target.closest('[data-queue]');if(b)loadExercise(queue[Number(b.dataset.queue)],Number(b.dataset.queue));};
 function requirePerson(){if(ctx.person())return true;ctx.toast('Adicione ou selecione uma pessoa primeiro.');return false;}
 function planEditor(plan){if(!requirePerson())return;planEdit=plan?.id||null;modal(plan?'Editar ficha':'Nova ficha',`<form id="plan-form"><label for="plan-name">Nome da ficha</label><input id="plan-name" maxlength="40" placeholder="Ex.: Treino A · Peito e tríceps" required value="${esc(plan?.name||'')}"><label for="plan-exercises">Exercícios · um por linha</label><textarea id="plan-exercises" rows="7" required placeholder="Supino reto&#10;Supino inclinado&#10;Tríceps na polia">${esc((plan?.exercises||[]).join('\n'))}</textarea><p class="hint">Ao abrir a ficha, usamos as últimas cargas desta pessoa. Você pode ajustar antes de salvar.</p><button class="primary">Salvar ficha</button><p id="plan-error" class="error" role="alert"></p></form>`);$('#plan-form').onsubmit=e=>{e.preventDefault();const name=$('#plan-name').value.trim(),exercises=[...new Set($('#plan-exercises').value.split('\n').map(s=>s.trim()).filter(Boolean))];if(!name||!exercises.length||exercises.length>50||exercises.some(s=>s.length>80)){$('#plan-error').textContent='Use um nome e de 1 a 50 exercícios, com até 80 caracteres cada.';return;}const d=ctx.data();d.plans=d.plans||[];const p={id:planEdit||crypto.randomUUID(),personId:ctx.person(),name,exercises,updatedAt:Date.now()};d.plans=d.plans.filter(x=>x.id!==p.id);d.plans.push(p);ctx.commit();$('#feature-dialog').close();};}
 $('#new-plan').onclick=()=>planEditor();
 $('#plans').onclick=e=>{const b=e.target.closest('button');if(!b)return;const p=(ctx.data().plans||[]).find(p=>p.id===b.dataset.id);if(!p)return;if(b.dataset.action==='edit')return planEditor(p);if(b.dataset.action==='delete'){p.deleted=true;p.updatedAt=Date.now();ctx.commit();ctx.toast('Ficha removida.',()=>{const row=ctx.data().plans.find(x=>x.id===p.id);row.deleted=false;row.updatedAt=Date.now();ctx.commit();});return;}const history=training();ctx.setType('training');startQueue(p.exercises.map(exercise=>({...history.find(e=>e.exercise.toLowerCase()===exercise.toLowerCase()),exercise})));};
 $('#repeat-workout').onclick=()=>{if(!requirePerson())return;const history=training();if(!history.length)return ctx.toast('Anote um treino para poder repeti-lo.');const last=history[0].date,items=history.filter(e=>e.date===last).reverse();modal('Repetir último treino',`<p class="subtle">${new Date(last+'T12:00:00').toLocaleDateString('pt-BR')} · ${items.length} registros</p><ul class="repeat-list">${items.map(e=>`<li>${esc(e.exercise)} <span>${e.weight} kg · ${e.sets} séries</span></li>`).join('')}</ul><p class="hint">Uma cópia fica pronta para hoje. Ajuste e salve cada exercício quando fizer.</p><button id="use-repeat" class="primary">Usar este treino</button>`);$('#use-repeat').onclick=()=>{$('#feature-dialog').close();ctx.setType('training');startQueue(items);};};
 $('#show-records').onchange=e=>{pref.records=e.target.checked;savePref();render();};
 const colors=['#285944','#355d8b','#8c4b37','#70508a','#827025','#52595d'];
 $('#edit-person').onclick=()=>{if(!requirePerson())return;const p=ctx.data().people.find(p=>p.id===ctx.person());personEdit=p.id;modal('Editar perfil',`<form id="edit-profile-form"><label for="edit-name">Nome</label><input id="edit-name" maxlength="32" value="${esc(p.name)}" required><label for="profile-color">Cor</label><select id="profile-color">${colors.map((c,i)=>`<option value="${c}" ${p.color===c?'selected':''}>${['Verde','Azul','Terracota','Roxo','Mostarda','Cinza'][i]}</option>`).join('')}</select><button class="primary">Salvar perfil</button><p class="error" id="profile-error" role="alert"></p></form>`);$('#edit-profile-form').onsubmit=e=>{e.preventDefault();const name=$('#edit-name').value.trim();if(!name||live(ctx.data().people).some(x=>x.id!==personEdit&&x.name.toLowerCase()===name.toLowerCase())){$('#profile-error').textContent='Escolha um nome diferente dos outros perfis.';return;}Object.assign(ctx.data().people.find(x=>x.id===personEdit),{name,color:$('#profile-color').value,updatedAt:Date.now()});ctx.commit();$('#feature-dialog').close();};};
 let end=0,remaining=0;try{({end=0,remaining=0}=JSON.parse(localStorage.getItem('mais-uma-rest')||'{}'));}catch{}
 const storeTimer=()=>localStorage.setItem('mais-uma-rest',JSON.stringify({end,remaining}));
 function tick(){const seconds=end?Math.max(0,Math.ceil((end-Date.now())/1000)):remaining;$('#rest-time').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;$('#pause-rest').textContent=end?'Pausar':'Continuar';$('#pause-rest').disabled=!end&&!remaining;if(end&&seconds===0){end=0;remaining=0;storeTimer();$('#rest-message').textContent='Descanso concluído. Pronto para mais uma?';ctx.toast('Descanso concluído.');}}
 document.querySelectorAll('[data-rest]').forEach(b=>b.onclick=()=>{end=Date.now()+Number(b.dataset.rest)*1000;remaining=0;$('#rest-message').textContent='';storeTimer();tick();});
 $('#pause-rest').onclick=()=>{if(end){remaining=Math.max(0,Math.ceil((end-Date.now())/1000));end=0;}else if(remaining){end=Date.now()+remaining*1000;remaining=0;}storeTimer();tick();};$('#reset-rest').onclick=()=>{end=0;remaining=0;storeTimer();$('#rest-message').textContent='';tick();};setInterval(tick,500);tick();
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
 $('#install-app').onclick=async()=>{if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;return;}modal('Instalar no celular','<p class="subtle">No iPhone: abra no Safari, toque em Compartilhar e depois em <strong>Adicionar à Tela de Início</strong>.</p><p class="subtle">No Android: abra o menu do Chrome e escolha <strong>Instalar app</strong> ou <strong>Adicionar à tela inicial</strong>.</p><p class="hint">Abra primeiro seu link do caderno neste navegador. Depois da primeira visita online, você pode anotar offline. Os registros serão enviados quando você abrir o app com internet.</p>');};
 if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>ctx.toast('Não foi possível preparar o modo offline. Tente reabrir com internet.'));
 function render(){const d=ctx.data(),person=ctx.person();$('#edit-person').hidden=!person;$('#detail-option').hidden=ctx.type()!=='training';$('#plans').innerHTML=live(d.plans||[]).filter(p=>p.personId===person).map(p=>`<div class="plan-row"><button data-id="${esc(p.id)}" data-action="start" class="text-button">${esc(p.name)} ↗</button><span>${p.exercises.length} exercícios</span><button data-id="${esc(p.id)}" data-action="edit" class="text-button">Editar</button><button data-id="${esc(p.id)}" data-action="delete" class="text-button">Excluir</button></div>`).join('');const prs=new Map();for(const e of training()){const max=Math.max(e.weight,...(e.series||[]).map(s=>s.weight));const k=e.exercise.toLowerCase();if(!prs.has(k)||max>prs.get(k).weight)prs.set(k,{exercise:e.exercise,weight:max});}$('#personal-records').hidden=!pref.records;$('#personal-records').innerHTML=pref.records?(prs.size?[...prs.values()].map(p=>`<div class="pr-row"><span>${esc(p.exercise)}</span><strong>${p.weight.toLocaleString('pt-BR')} kg</strong></div>`).join(''):'<p class="hint">Seus recordes aparecem depois do primeiro exercício.</p>'):'';for(const b of document.querySelectorAll('[data-person]')){const p=d.people.find(p=>p.id===b.dataset.person);if(p?.color&&colors.includes(p.color)){b.querySelector('.avatar').style.background=p.color;b.querySelector('.avatar').style.color='white';}}renderQueue();}
 return {render,reset(){toggle(false);},personChanged(){queue=[];active=-1;renderQueue();},edit(row){toggle(!!row.series?.length,row.series);},entryExtras(){return detailed&&ctx.type()==='training'?{series:readRows()}:{};},saved(){if(queue[active])queue[active].done=true;renderQueue();},describe(e){return e.series?.length?e.series.map(s=>`${s.reps} × ${s.weight.toLocaleString('pt-BR')} kg`).join(' · '):`${e.sets} séries × ${e.reps} repetições`;}};
}

